### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by alsam2009** [vercel/next-learn#354]
Error resolving EcmaScript Modules request
unable to resolve module "@" with subpath "/app/ui/fonts"
It was not possible to find the requested file.
    Parsed request as written in source code: module "@" with subpath "/app/ui/fonts"
    Path where resolving has started: [project]/app/ui/acme-logo.tsx
    Type of request: EcmaScript Modules request
    Import map: aliased to relative "./app/ui/fonts" inside of [project]/

I can't see fonts folder in /app/ui/ both in local project and in repo. 
What's problem?

**Comment by StephDietz** [comment]
@alsam2009 thank you for the feedback! this has been fixed :)

**Comment by gnchrv** [comment]
Sorry for reopening the issue, but `@app/ui/fonts.ts` is still missing in [the starter example](https://github.com/vercel/next-learn/tree/main/dashboard/starter-example/app/ui) which produces the import error in `@app/ui/acme-logo.tsx` 😬 Had to manually copy it from [the final version](https://github.com/vercel/next-learn/blob/main/dashboard/final-example/app/ui/fonts.ts).

May be the problem behind the #522 issue as well.

**Comment by Cyclodex** [comment]
How has this been fixed? I just tried the tutorial, and the build is failing because there is no fonts file or directory.

> Cannot find module '@/app/ui/fonts' or its corresponding type declarations.ts(2307)

**Comment by tiagomatos8** [comment]
Same problem here.

`./app/ui/acme-logo.tsx:2:26
Type error: Cannot find module '@/app/ui/fonts' or its corresponding type declarations.

  1 | import { GlobeAltIcon } from '@heroicons/react/24/outline';
> 2 | import { lusitana } from '@/app/ui/fonts';`

**Comment by Bopzor** [comment]
For those like me who struggled too long because of this... just keep following the tutorial until at least chapter 3 (included)...
The folder does not exist at first, but the tutorial indicates us to created during chapter 3.
