### ISSUE TITLE
npm run seed error

### ISSUE THREAD

**Issue by fb12424** [vercel/next-learn#476]
```
> seed
> node -r dotenv/config ./scripts/seed.js

node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (D:\works\2023\nextjs-yfb\nextjs-dashboard\node_modules\ws\lib\websocket.js:1016:13)
    at ClientRequest.<anonymous> (D:\works\2023\nextjs-yfb\nextjs-dashboard\node_modules\ws\lib\websocket.js:864:5)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

Node.js v18.17.0
```

**Comment by StephDietz** [comment]
@fb12424 thanks for the feedback! Can you provide more information and confirm this issue is still persisting and was not just a network issue?

**Comment by Sedjro09** [comment]
No it was not a network issue. I had a same issue. 

> seed
> node -r dotenv/config ./scripts/seed.js

node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOENT ep-divine-dew-67834200-pooler.us-east-1.postgres.vercel-storage.com
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (C:\Users\Arsene\Desktop\Soft Vodooz\ReactJS\nextjs-dashboard\node_modules\ws\lib\websocket.js:1016:13)       
    at ClientRequest.<anonymous> (C:\Users\Arsene\Desktop\Soft Vodooz\ReactJS\nextjs-dashboard\node_modules\ws\lib\websocket.js:864:5) 
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'getaddrinfo',
  hostname: 'ep-divine-dew-67834200-pooler.us-east-1.postgres.vercel-storage.com'
}

Node.js v20.9.0

**Comment by wanglin1329** [comment]
![Uploading 微信图片_20231228230029.png…]()



@joelcipriano  I'm encountering an error at the same spot,  I've installed "dotenv" package but am still facing errors.

**Comment by fb12424** [comment]
> @fb12424 thanks for the feedback! Can you provide more information and confirm this issue is still persisting and was not just a network issue?

It was a network problem in my area. It was fixed after turning on the powershell network agent.

**Comment by leerob** [comment]
I am not able to reproduce this. Please open a new issue if you are still having trouble here. Thank you!

**Comment by blakefan** [comment]
> > @fb12424 thanks for the feedback! Can you provide more information and confirm this issue is still persisting and was not just a network issue?
> 
> It was a network problem in my area. It was fixed after turning on the powershell network agent.我所在区域出现了网络问题，通过启用 PowerShell 网络代理后得以解决。

I have set up a proxy but still cannot make the same error. How did you set up the proxy

> > @fb12424 thanks for the feedback! Can you provide more information and confirm this issue is still persisting and was not just a network issue?
> 
> It was a network problem in my area. It was fixed after turning on the powershell network agent.

I have set up a proxy but still cannot make the same error. How did you set up the proxy
